name: Push
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: actions/setup-go@v1
        with:
          go-version: "1.13"
      - run: go test ./...
